### ISSUE TITLE
Using documented and stable Nix CLI

### ISSUE THREAD

**Issue by DamienCassou** [jonascarpay/template-haskell#10]
The CI.yml of the project uses `nix build` which is undocumented ([except in the wiki](https://nixos.wiki/wiki/Nix_command)), experimental and not installed by default with the rest of Nix.
I suggest using `nix-build` instead. I can send a PR.

**Comment by jonascarpay** [comment]
> not installed by default with the rest of Nix

I did not know this, is it not available on your installation?

I tend to like `nix build` more because it's output is easier to understand, but if it's not always available it might be better to use `nix-build` instead.

**Comment by DamienCassou** [comment]
> I did not know this, is it not available on your installation?

This [wiki page](https://nixos.wiki/wiki/Nix#Nix_commands) says that the `nix` command is undocumented and references [the nix command wiki page](https://nixos.wiki/wiki/Nix_command) which says this is experimental. This latter page also discusses version 2.4 which is [not released yet](https://github.com/NixOS/nix/releases).

Nevertheless, it seems the `nix` program and its commands are activated on my system and in GitHub Actions. I just don't understand exactly why.

**Comment by DamienCassou** [comment]
I asked the question in discourse and [got some answers explaining differences](https://discourse.nixos.org/t/state-of-the-nix-program-and-its-subcommands/12491/2).

**Comment by jonascarpay** [comment]
For now I'm gonna say it's better to just use the `nix` command. At work I've moved all our stuff to use it as well and we haven't had any issues. Just the fact that it tells you per line what derivation produced some piece of output makes it much nicer to use than `nix-build`. If at some point there is a more idiomatic way of doing things with the same quality of output, or if there's some other issue with it, I'd be happy to move to some other build method.

**Comment by DamienCassou** [comment]
This makes sense, thank you.
