### ISSUE TITLE
Why is cache deactivated for stack-build?

### ISSUE THREAD

**Issue by DamienCassou** [jonascarpay/template-haskell#11]
`actions/cache@v2` is [deactivated in `stack-build` job of CI.yml](https://github.com/jonascarpay/template-haskell/blob/878f1016d95a39eb83ab9de0c6cf5cc636a13809/.github/workflows/CI.yaml#L43). Can you please explain the reason? I think a comment in CI.yml would be best so others don't ask the same question.

**Comment by jonascarpay** [comment]
Thanks, addressed in 7a69dc89e865b21ac3470f517e74cd0dd41b3efb

**Comment by DamienCassou** [comment]
Thank you!
