### ISSUE TITLE
Bug: wizard doesn't work if git doesn't have email or name set

### ISSUE THREAD

**Issue by wuyoli** [jonascarpay/template-haskell#14]
## to reproduce:
1. unset name and email from git config
2. run wizard 
3. give project name
4. wizard exits without explaination

## expected behaviour:
ask for email and name and set this with `git config` for the local repo or at least an error message

**Comment by jonascarpay** [comment]
Thanks for reporting. This should be fixed in 04c99e58e05cf163eebdd17d7dff870657b4b118
