### ISSUE TITLE
How to check HLS availability?

### ISSUE THREAD

**Issue by Tyrn** [jonascarpay/template-haskell#16]
Hi,

Previously I used GHCup and AstroNvim (Neovim). HLS worked uneventfully. Now I've been trying `template-haskell` and it doesn't seem to work. All I can tell, that the necessary packages are present:
```
[alexey@gaucho hello]$ type haskell-language-server
haskell-language-server is /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/haskell-language-server
[alexey@gaucho hello]$ type haskell-language-server-wrapper
haskell-language-server-wrapper is /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/haskell-language-server-wrapper
```
What else should I check?

**Comment by jonascarpay** [comment]
Weird, I personally also use nvim, and [this single line](https://github.com/jonascarpay/nix/blob/master/home/vim/default.nix#L136) of config has been sufficient to get HLS working. Let's start by checking if HLS works in isolation. Can you do a new checkout and tell me what happens if you run `haskell-language-server`? For reference, this is what it looks like for me:

```shell
$ cp -r template-haskell hls-test
$ cd hls-test/
$ ./wizard.sh 
...
All set!
$ nix develop
nix-shell$ haskell-language-server
2024-03-04T12:42:04.376306Z | Info | haskell-language-server version: 2.4.0.0 (GHC: 9.4.8) (PATH: /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/.haskell-language-server-9.4.8-unwrapped)
2024-03-04T12:42:04.377005Z | Info | Directory: /home/jmc/Dev/hls-test
2024-03-04T12:42:04.377180Z | Info | Logging heap statistics every 60.00s
 ghcide setup tester in /home/jmc/Dev/hls-test.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/jmc/Dev/hls-test
Found 4 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  (/home/jmc/Dev/hls-test/hie.yaml)

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
...
Files that failed:
 * /home/jmc/Dev/hls-test/bench/Main.hs

Completed (3 files worked, 1 file failed)

```

**Comment by jonascarpay** [comment]
I'm not sure, maybe there's some vestigial ghcup stuff in your $PATH? What OS are you on?
Either way, it seems like your HLS works fine, so my guess would be nvim is not picking it up correctly.
What's your `:LspInfo` output after you open a Haskell file? Mine is 

```
Press q or <Esc> to close this window. Press <Tab> to view server doc.
 
 Language client log: /home/jmc/.local/state/nvim/lsp.log
 Detected filetype:   haskell
 
 1 client(s) attached to this buffer: 
 
 Client: hls (id: 1, bufnr: [1])
 	filetypes:       haskell, lhaskell
 	autostart:       true
 	root directory:  /home/jmc/Dev/hls-test
 	cmd:             /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/haskell-language-server-wrapper --lsp
 	version:   haskell-language-server version: 2.4.0.0 (GHC: 9.4.8) (PATH: /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/haskell-language-server-wrapper)
 
 Configured servers list: nil_ls, hls, ccls, bashls, rust_analyzer, pyright, ruff_lsp
 ```

**Comment by Tyrn** [comment]
My OS is Manjaro (Arch family). I've got two boxes with similar installation. On one I use GHCup, and HLS just works. `:LspInfo` shows `haskell-language-server-wrapper` with options, indeed.

On another box GHCup removed, `nix develop` on `template-haskell`. `:LspInfo` shows no signs of the language server; there's log:
```
...
[START][2024-03-04 21:40:13] LSP logging initiated
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        'Found "/home/alexey/spaces/haskell/hello/hie.yaml" for "/home/alexey/sp'
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        'aces/haskell/hello/a"\n'
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "Run "
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "entered for haskell-language-server-wrapper(has"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "kell-language-server-wrapper) V"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "ersion 2.5.0.0 x86_64 ghc-9.2.8\nCurrent directory: /home/alexey/spaces"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "/haskell/hello\nOperati"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "ng system: linux\nArguments"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        ': ["--lsp","'
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        '--logfile","/tmp/nix-shel'
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "l.6RMxjF"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "/nvim.al"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "exey/Jqi"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "Q7H/0-ha"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "skell-"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "language"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "-server."
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        'log"]\nCradle d'
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "irectory"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        ": /home/al"
[ERROR][2024-03-04 21:40:13] .../vim/lsp/rpc.lua:734    "rpc"   "haskell-language-server-wrapper"       "stderr"        "exey/sp"
...
```
The log is much longer.

**Comment by jonascarpay** [comment]
Mine says ` Client: hls (id: 1, bufnr: [1])`, but yours says ` Client: haskell-tools.nvim (id: 1, bufnr: [1])`. I'm not familiar with haskell-tools, but it might be trying to be clever about finding your HLS binary and somehow bypass the intended one from the local shell. A cursory browse suggests that https://github.com/mrcjkb/haskell-tools.nvim/issues/200 is people having a similar issue.

**Comment by Tyrn** [comment]
Thank you very much for your effort above and beyond the call of duty!

I'm thinking what my next step should be. I don't use NixOS, so I can't just appropriate your config :) . AstroNvim served me wonderfully, neither breaking beyond hope nor requiring profound expertise. There's no such thing as a free lunch, unfortunately.

Right now I'm stuck with the so-called [Astrocommunity Pack for Haskell](https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/haskell). This means that I can't even edit it. The remaining option is to create something like `~/.config/nvim/lua/user/plugins/haskell.lua` on my own, without the use of `haskell-tools`. It's just as easy as with any Neovim installation, if not easier—provided you know what you're doing...

Any suggestion or link is welcome.

**Comment by Tyrn** [comment]
First step: moved the [init.lua](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/haskell/init.lua) from the Astrocommunity Haskell Pack (already removed from my config) to `/.config/nvim/lua/user/plugins/haskell.lua`. Still works, not a character changed. Almost too good to be true. Great engineering, AstroNvim. Now I can do with it ([init.lua](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/haskell/init.lua), now `/.config/nvim/lua/user/plugins/haskell.lua`) whatever I please. If I only knew how to get rid of `haskell-tools`.

**Comment by jonascarpay** [comment]
(going to assume this is completed)
