### ISSUE TITLE
Making this project an actual template

### ISSUE THREAD

**Issue by DamienCassou** [jonascarpay/template-haskell#3]
Hi,

I'm trying template-haskell for my own project. I think it would be useful if template-haskell was an actual GitHub template instead of just a project. Here is an actual GitHub template: https://github.com/nix-dot-dev/getting-started-nix-template. As you can see, the main page of this project has a big green "Use this template" button.

Basically, you just have to check 1 checkbox in the GitHub settings page of your project: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository.

**Comment by jonascarpay** [comment]
Thanks for the tip, done!
