### ISSUE TITLE
Some feedback on the blog post

### ISSUE THREAD

**Issue by DamienCassou** [jonascarpay/template-haskell#4]
Hi,

I'm not sure where you want (or even whether you want) feedback on your blog post [The working programmer’s guide to setting up Haskell projects](https://jonascarpay.com/posts/2021-01-28-haskell-project-template.html) so I'm writing it here.

There is a section "Making one yourself" that is a sub-section of "Project setup". I'm not sure if "Making one yourself" should be done after using `template-haskell` or only if the user doesn't want to use `template-haskell`. I think a clarifying sentence at the beginning of the section would help.

> It doesn’t really matter how you do this (you probably already have a preferred way already).

I suggest giving an example that differs from the one used by `template-haskell`, e.g., using Stack. Giving an example will make make it perfectly explicit what the paragraph is all about.

> Getting the tools we want is a matter of adding them to the tools section in the shellFor.

I suggest saying which file you are talking about. Giving an example would also help. 

Why isn't "hlint" included in the `shellFor` by the way? What if I want GitHub Actions to run hlint on all my files?

Thank you for all your work.

**Comment by jonascarpay** [comment]
Thanks for your feedback! I've incorporated this in https://github.com/jonascarpay/jonascarpay.github.io/commit/6156be4213a84e9123862d74c59db4b035e194a0, let me know if you have any other suggestions/questions.

> Why isn't "hlint" included in the shellFor by the way? What if I want GitHub Actions to run hlint on all my files?

Oh good catch, I'm not sure why it's not included, but I'll add it back in.
