### ISSUE TITLE
MacOS Big Sur requires nixpkgs-unstable instead of 2009

### ISSUE THREAD

**Issue by mputz86** [jonascarpay/template-haskell#9]
Just want to leave a note here for somebody stumbling over this MacOS+Nix specific issue (like me, quite new to Nix and was hooked by the blog post to migrate my Haskell projects :)).

Maybe it is worth to mention it in the README, maybe not.

The fix is to replace `nixpkgs-2009` in `pkgs.nix` with `nixpkgs-unstable`.

**Comment by jonascarpay** [comment]
Oh interesting, what error do you get? Maybe it's worth just defaulting to `unstable` altogether.

**Comment by mputz86** [comment]
Oh, sorry for not giving all information initially:
It is this issue https://github.com/input-output-hk/haskell.nix/issues/982 . So on macOS Big Sur they changed a lot regarding the linker. In essence, some libs in `/nix/store/...` refer to no longer existing libs in `/usr/lib/system/`.

The error message is `ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64`, in full length:

```
ld: warning: /nix/store/c8j0gfzbkxblb9s64anmpxcsrq4hv5ih-libiconv-osx-10.12.6/lib/libiconv.dylib, ignoring unexpected dylib file
building
ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
Preprocessing library for code-page-0.2.1..
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
error: builder for '/nix/store/wf3k5rmbmsmbpfvsqmlnn4yvcbjgqdpy-binary-orphans-lib-binary-orphans-1.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > Warning: The flag --disable-executable-profiling is deprecated. Please use
       > --disable-profiling instead.
       > building
       > Preprocessing library for binary-orphans-1.0.1..
       > Building library for binary-orphans-1.0.1..
       > [1 of 1] Compiling Data.Binary.Orphans ( src/Data/Binary/Orphans.hs, dist/build/Data/Binary/Orphans.o, dist/build/Data/Binary/Orphans.dyn_o )
       > ld: warning: /nix/store/c8j0gfzbkxblb9s64anmpxcsrq4hv5ih-libiconv-osx-10.12.6/lib/libiconv.dylib, ignoring unexpected dylib file
       > ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
       > clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
       > `cc' failed in phase `Linker'. (Exit code: 1)
       For full logs, run 'nix log /nix/store/wf3k5rmbmsmbpfvsqmlnn4yvcbjgqdpy-binary-orphans-lib-binary-orphans-1.0.1.drv'.
```

Does this help? :)

**Comment by jonascarpay** [comment]
Thanks for the detailed report. I just moved master to use `nixpkgs-unstable` in https://github.com/jonascarpay/template-haskell/commit/d244783c816db99221931d37e89b79d7b968cb10, since it seems like `unstable` is the better supported branch at this time. Maybe by the time 2105 hits we'll move to that instead.
